services:
  order_service:
    build: .
    container_name: order_service
    ports:
      - "8008:8000"
    volumes:
      - .:/app
    depends_on:
      - order_db
      - migrations
      - zookeeper
      - kafka

  migrations:
    build: .
    command: alembic upgrade head
    depends_on:
      - order_db

  order_db:
    image: postgres:14
    container_name: order_db
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      - "9093:9093"

  order_outbox_processor:
    build: .
    container_name: order_outbox_processor
    command: python run_outbox_processor.py
    depends_on:
      - order_db
      - zookeeper
      - kafka

  order_payment_consumer:
    build: .
    container_name: order_payment_consumer
    command: python run_payment_consumer.py
    depends_on:
      - order_db
      - zookeeper
      - kafka